### PR TITLE
Add possibility to customise collection view

### PR DESCRIPTION
**Pull request by SRozhina**
Currently there is no possibility to customise collection view: set different cell paddings and specify number of grid columns. Also because of layout state property is private there is no possibility to configure cell before transition in willTransition depending on the current layout state.

**Commit summary:** 

- I extended init with 3 new property: cellHeightPadding, cellWidthPadding and gridLayoutCountOfColumns. All this properties have default values as before for backwards compatibility. 

- Now DisplaySwitchLayout has layoutState read-only property for configure cell before transition. 

Now there is possibility to make own design of collection view.

### CODE REVIEW

**Comment by freaqed** [comment]
Hey, @SRozhina!
Thanks for contributing!

Consider next time making `cellPadding` of type `CGSize` (or `CGPoint` which should be more understandable), so you won't need two separate variables to handle height/width.

**Comment by SRozhina** [comment]
Thanks. And could you please publish changed pod to CocoaPods Trunk. When I install DisplaySwitcher I have the same pod - it's even not updated to Swift 4. But when I forked the project it was.

**Comment by freaqed** [comment]
Of course. But I'm not sure we can make it today.
You can specify source directly in your pod file by specifying `:git` and `:branch` values until we publish it.

**Comment by SRozhina** [comment]
Okay, thanks :)

**Comment by SRozhina** [comment]
I made a small update PR #36 related to current PR for your comment. Please, take a look.

**Pull request merged**
